version: 0.1

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y zip
  build:
    commands:
      # Clone the GitHub repository
      - git clone https://github.com/FlorinManaila/Redis.git
      # Change to the cloned repository directory
      - pwd
      - cd ../../Layers
      - pwd
      - cd Redis
      # Upload CF template to S3
      - aws s3 cp CloudFormation/AWSTemplateFormatVersion:\ 2010-09-09.yml s3://redis-cicd/v.1.1/
      - aws s3 cp CloudFormation/AWSTemplateFormatVersion:\ 2010-09-09.yml s3://redis-cicd/latest/
      # Create a zip archive for lambdas and upload archives to S3
      - zip -j FlexibleSubscription-CheckState.zip Lambda/FlexibleSubscription-CheckState.py
      - zip -j FlexibleSubscription-CFResponse.zip Lambda/FlexibleSubscription-CFResponse.py
      - zip -j FlexibleSubscription-Handler.zip Lambda/FlexibleSubscription-Handler.py
      - aws s3 cp FlexibleSubscription-CheckState.zip s3://redis-cicd/latest/
      - aws s3 cp FlexibleSubscription-CFResponse.zip s3://redis-cicd/latest/
      - aws s3 cp FlexibleSubscription-Handler.zip s3://redis-cicd/latest/
      - aws s3 cp FlexibleSubscription-CheckState.zip s3://redis-cicd/v.1.1/
      - aws s3 cp FlexibleSubscription-CFResponse.zip s3://redis-cicd/v.1.1/
      - aws s3 cp FlexibleSubscription-Handler.zip s3://redis-cicd/v.1.1/
      # Create a zip archive for layers and upload archives to S3
      - cd Redis/Layers
      - ls
      - zip -r requests_layer.zip requests_layer
      - zip -r secrets_layer.zip secrets_layer
      - aws s3 cp requests_layer.zip s3://redis-cicd/v.1.1/
      - aws s3 cp secrets_layer.zip s3://redis-cicd/v.1.1/
      - aws s3 cp requests_layer.zip s3://redis-cicd/latest/
      - aws s3 cp secrets_layer.zip s3://redis-cicd/latest/

      