version: 0.1

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y zip
  build:
    commands:
      # Clone the GitHub repository
      - git clone https://github.com/FlorinManaila/Redis.git
      # Change to the cloned repository directory
      - cd Redis
      # Create a zip archive of the files you want to package
      - zip FlexibleSubscription-CheckState.zip Lambda/FlexibleSubscription-CheckState.py
      - zip FlexibleSubscription-CFResponse.zip Lambda/FlexibleSubscription-CFResponse.py
      - zip FlexibleSubscription-Handler.zip Lambda/FlexibleSubscription-Handler.py
      - zip -r requests_layer.zip Layers/requests_layer
      - zip -r secrets_layer.zip Layers/secrets_layer
      # Upload the zip archive to an S3 bucket
      - aws s3 cp FlexibleSubscription-CheckState.zip s3://redis-cicd/v.1.1/
      - aws s3 cp FlexibleSubscription-CFResponse.zip s3://redis-cicd/v.1.1/
      - aws s3 cp FlexibleSubscription-Handler.zip s3://redis-cicd/v.1.1/
      - aws s3 cp requests_layer.zip s3://redis-cicd/v.1.1/
      - aws s3 cp secrets_layer.zip s3://redis-cicd/v.1.1/
      - aws s3 cp CloudFormation/AWSTemplateFormatVersion:\ 2010-09-09.yml s3://redis-cicd/v.1.1/
      - aws s3 cp FlexibleSubscription-CheckState.zip s3://redis-cicd/latest/
      - aws s3 cp FlexibleSubscription-CFResponse.zip s3://redis-cicd/latest/
      - aws s3 cp FlexibleSubscription-Handler.zip s3://redis-cicd/latest/
      - aws s3 cp requests_layer.zip s3://redis-cicd/latest/
      - aws s3 cp secrets_layer.zip s3://redis-cicd/latest/
      - aws s3 cp CloudFormation/AWSTemplateFormatVersion:\ 2010-09-09.yml s3://redis-cicd/latest/
      